apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-adapter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-adapter
  template:
    metadata:
      labels:
        app: metrics-adapter
    spec:
      containers:
        - name: metrics-adapter
          image: metrics-adapter:0.007
          args: ["--backend=http://hephaestus-gui:8080"]
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-adapter
  namespace: monitoring
spec:
  selector:
    app: hephaestus-gui
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080

