import com.example.droolsprototype.demo.tests.utils.TestConstants;
import io.github.hephaestusmetrics.model.metrics.Metric;
import com.example.droolsprototype.execution.ExecutionService;
import com.example.droolsprototype.DroolsPrototypeApplication;

rule "enforce_pod_critical_value"
    dialect "mvel"
    when
        metric : Metric(
            name == "critical_metric",
            value > TestConstants.POD_CRITICAL_VALUE_LIMIT
        )
        executor: ExecutionService()
    then
        executor.deletePod(metric.labels.get("namespace"), metric.labels.get("pod"));
end
