import com.example.droolsprototype.demo.performancetests.utils.TestConstants;
import io.github.hephaestusmetrics.model.metrics.Metric;
import com.example.droolsprototype.execution.ExecutionService;
import com.example.droolsprototype.DroolsPrototypeApplication;

rule "enforce_pod_cpu"
    dialect "mvel"
    when
        metric : Metric(
            labels["__name__"] == "container_cpu_usage_seconds_total",
            labels["namespace"] == "sock-shop",
            labels["container"] == "front-end",
            value > TestConstants.FRONT_END_SOCK_SHOP_CPU_LIMIT
        )
        executor: ExecutionService()
    then
        executor.execute("change_pod_cpu_request", metric.labels.get("pod"));
end
